
import { Client } from '@notionhq/client';
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

// Load environment variables
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const NOTION_API_KEY = process.env.NOTION_API_KEY;
const NOTION_DATABASE_ID = process.env.NOTION_DATABASE_ID || '714b76dc6cde47f696309c5f70d189e9';
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!NOTION_API_KEY) {
    console.error('❌ Error: NOTION_API_KEY is not defined in .env.local');
    process.exit(1);
}

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
    console.error('❌ Error: Supabase credentials are not defined in .env.local');
    process.exit(1);
}

// Initialize Clients
const notion = new Client({ auth: NOTION_API_KEY });
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

// Types
interface NotionDailyRecord {
    date: string;
    cas5: number;
    cas1: number;
    gif: number;
    car1: number;
    car2: number;
    person: number;
    pos: number;
    // Raw data identifying info
    notion_page_id: string;
}

// Fetch all data from Notion with pagination
async function fetchAllNotionData(): Promise<NotionDailyRecord[]> {
    console.log('📡 Fetching data from Notion...');

    let allResults: any[] = [];
    let hasMore = true;
    let cursor: string | undefined = undefined;

    try {
        while (hasMore) {
            const response = await notion.databases.query({
                database_id: NOTION_DATABASE_ID,
                start_cursor: cursor,
                sorts: [
                    {
                        property: '날짜',
                        direction: 'ascending',
                    },
                ],
            });

            allResults = [...allResults, ...response.results];
            hasMore = response.has_more;
            cursor = response.next_cursor || undefined;

            console.log(`   Fetched ${allResults.length} records so far...`);
        }
    } catch (error: any) {
        console.error('❌ Error fetching from Notion:', error.message);
        throw error;
    }

    // Transform data - strict 1:1 mapping
    console.log('🔄 Transforming data (Raw Copy Mode)...');
    const records: NotionDailyRecord[] = [];

    for (const page of allResults) {
        if (!('properties' in page)) continue;

        const props = page.properties;
        const date = props['날짜']?.date?.start;

        if (!date) {
            console.warn(`Original Record ID: ${page.id} has no date. Skipping.`);
            continue;
        }

        const cas5 = props['cas5']?.number || 0;
        const cas1 = props['cas1']?.number || 0;
        const gif = props['gif']?.number || 0;
        const car1 = props['car1']?.number || 0;
        const car2 = props['car2']?.number || 0;
        const person = props['person']?.number || 0;
        const pos = props['Pos']?.number || 0;

        records.push({
            date,
            cas5,
            cas1,
            gif,
            car1,
            car2,
            person,
            pos,
            notion_page_id: page.id
        });
    }

    return records;
}

async function migrateData() {
    try {
        console.log('🚀 Starting MIGRATION V2 (Raw Copy)...');

        const records = await fetchAllNotionData();
        console.log(`✅ Found ${records.length} total records in Notion.`);

        if (records.length === 0) {
            console.log('⚠️ No records found to migrate.');
            return;
        }

        // Verify date coverage
        const years = new Set(records.map(r => r.date.substring(0, 4)));
        console.log(`📅 Years found in data: ${Array.from(years).sort().join(', ')}`);

        // Prepare for Supabase insert
        const supabasePayload = records.map(record => {
            const income = record.cas5 + record.cas1 + record.gif + record.car1 + record.car2;
            const expense = record.person;
            const net_income = income - expense;
            const diff = net_income - record.pos;

            return {
                // id will be auto-generated by uuid
                date: record.date,
                cas5: record.cas5,
                cas1: record.cas1,
                gif: record.gif,
                car1: record.car1,
                car2: record.car2,
                person: record.person,
                pos: record.pos,
                income,
                expense,
                net_income,
                diff,
                updated_at: new Date().toISOString()
            };
        });

        console.log('💾 Inserting data into Supabase (No Aggregation)...');

        // Insert in batches
        const batchSize = 50;
        let insertedCount = 0;

        for (let i = 0; i < supabasePayload.length; i += batchSize) {
            const batch = supabasePayload.slice(i, i + batchSize);

            const { error } = await supabase
                .from('daily_income')
                .insert(batch); // strict insert, no upsert

            if (error) {
                console.error(`❌ Error inserting batch ${i / batchSize + 1}:`, error.message);
                throw error;
            }

            insertedCount += batch.length;
            console.log(`   Processed ${insertedCount} / ${supabasePayload.length} records.`);
        }

        console.log('✨ Migration completed successfully!');
        console.log(`Total records inserted: ${insertedCount}`);

    } catch (error: any) {
        console.error('❌ Migration failed:', error.message);
        process.exit(1);
    }
}

migrateData();
